[package]
name = "hsm-server"
version.workspace = true
edition.workspace = true

[dependencies]
hsm-ipc.workspace = true

rodio.workspace = true
smol.workspace = true
ctrlc.workspace = true
futures-concurrency.workspace = true
atomic_enum.workspace = true

mpris-server = "0.9.0"
